# Update the frontend workflow file
name: Deploy Frontend to Cloud Run

on:
  push:
    branches: [ main ]
    paths: [ 'src/**', 'public/**', 'package.json', 'vite.config.ts' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker to use gcloud
      run: gcloud auth configure-docker

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy fabtracko-frontend \
          --source . \
          --region asia-south1 \
          --allow-unauthenticated \
          --port 8080


