name: Deploy Frontend to Cloud Run

on:
  push:
    branches: [ main ]
    paths: [ 'src/**', 'public/**', 'package.json', 'vite.config.ts' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: fabtracko
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker to use gcloud
      run: gcloud auth configure-docker

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy fabtracko-frontend \
          --source . \
          --region asia-south1 \
          --allow-unauthenticated \
          --port 8080
