# Update the backend workflow file
name: Deploy Backend to Cloud Run
on:
  push:
    branches: [ main ]
    paths: [ 'backend/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker to use gcloud
      run: gcloud auth configure-docker

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy fabtracko-backend \
          --source ./backend \
          --region asia-south1 \
          --allow-unauthenticated \
          --port 8080 \
          --update-env-vars="NODE_ENV=production" \
          --update-env-vars="JWT_SECRET=${{ secrets.JWT_SECRET }}" \
          --update-env-vars="MONGODB_URI=${{ secrets.MONGODB_URI }}"

