# Create a new backend workflow that builds the container

name: Deploy Backend to Cloud Run

on:
  push:
    branches: [ main ]
    paths: [ 'backend/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: fabtracko

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker to use gcloud
      run: gcloud auth configure-docker

    - name: Build and Push Docker Image
      run: |
        cd backend
        docker build -t gcr.io/fabtracko/fabtracko-backend:${{ github.sha }} .
        docker push gcr.io/fabtracko/fabtracko-backend:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy fabtracko-backend \
          --image gcr.io/fabtracko/fabtracko-backend:${{ github.sha }} \
          --region asia-south1 \
          --allow-unauthenticated \
          --port 8080 \
          --set-env-vars="NODE_ENV=production,JWT_SECRET=${{ secrets.JWT_SECRET }},MONGODB_URI=${{ secrets.MONGODB_URI }}"

